name: Cmake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Tar.Gz_artifact
        path: ${{ github.workspace }}/artifacts/*.tar.gz
